title: Rando Dev
email: example@example.com
description: >
  This is the Collider Jekyll Theme.
baseurl: ""
url: "https://jekyll-theme-collider.netlify.com"
hosted_url: ""
github_username: ""
linked_in_profile: ""
full_name: Rando Dev
user_description: Software Engineer
disqus:
  shortname: jekyll-theme-collider-netlify-com

markdown: kramdown
plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  blog_posts:
    output: true
    permalink: /collection/:name
  blog_tags:

pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  collection: 'blog_posts'
  trail:
    before: 2
    after: 2

permalink: pretty

sass:
  sass_dir: _sass
